# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Image {
  path: String! # path, not url, because it can be a local image
  height: Int!
  width: Int!
}

enum TitlePageSubType {
  SIMPLE
  IMAGE
  # VIDEO
  # MARKDOWN
}

type TitlePage {
  title: String!
  subType: TitlePageSubType
  image: Image
}

type Query {
  titlePage: TitlePage
}
